version: '3.8'

services:
  app:
    image: node-js-app-cloud-run-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://myuser:MyStr0ngP@ssw0rd!@mysql:3306/ztestdb
    volumes:
      - .:/usr/src/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ztestdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: MyStr0ngP@ssw0rd!
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
